//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var15.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartament
    {
        public int IdApartament { get; set; }
        public int IdHouse { get; set; }
        public int NumberApartament { get; set; }
        public decimal Area { get; set; }
        public int CountRoom { get; set; }
        public int Section { get; set; }
        public int Floor { get; set; }
        public int IdStatus { get; set; }
        public decimal AddingCost { get; set; }
        public decimal BuildingCost { get; set; }
    
        public virtual HousInComplex HousInComplex { get; set; }
        public virtual Status Status { get; set; }
    }
}
