//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var15.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complex()
        {
            this.HousInComplex = new HashSet<HousInComplex>();
        }
    
        public int IdComplex { get; set; }
        public string NameComplex { get; set; }
        public int IdStatus { get; set; }
        public int IdCity { get; set; }
        public decimal AddingCost { get; set; }
        public decimal BuildingCost { get; set; }
    
        public virtual City City { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HousInComplex> HousInComplex { get; set; }
    }
}
