//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Var15.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HousInComplex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HousInComplex()
        {
            this.Apartament = new HashSet<Apartament>();
        }
    
        public int IdHouseInComplex { get; set; }
        public int IdStreet { get; set; }
        public string NumberHouse { get; set; }
        public decimal BuildingCostHouse { get; set; }
        public decimal AddingCostApartament { get; set; }
        public int IdComplex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartament> Apartament { get; set; }
        public virtual Complex Complex { get; set; }
        public virtual Street Street { get; set; }
    }
}
